- set_fact: outer_item="{{item}}"

- name: Create a sandbox instance
  local_action:
     module: ec2
     exact_count: 1
     count_tag:
       Name: "{{ outer_item.INSTANCES_NAME }}"
     instance_profile_name: "{{ IAM_ROLE_NAME }}"
     key_name: "{{ outer_item.KEY_NAME_IN }}"
     group_id: "{{ outer_item.SECURITY_GROUP_IN }}"
     instance_type: "{{ outer_item.INSTANCE_TYPE_IN }}"
     image: "{{ outer_item.IMAGE_IN }}"
     wait: true
     region: "{{ outer_item.REGION_IN }}"
     vpc_subnet_id: "{{ outer_item.SUBNET_ID_IN }}"
     instance_tags: { "Name" : "{{ outer_item.INSTANCES_NAME }}" }
     assign_public_ip: no
  register: ec2
  until: ec2|success
  ignore_errors: True
  retries: 5
  delay: 30

- name: debug ec2
  debug: "msg='ec2 details: {{ec2.tagged_instances}}'"

- name: Getting ec2 ips
  debug: "msg='ec2 ips: {{ item.private_ip }}'"
  with_items: "{{ ec2.tagged_instances }}"

- name: Getting ec2 instance_ids
  debug: "msg='instance_ids: {{ item.id }}'"
  with_items: "{{ ec2.tagged_instances }}"

- name: Add the newly IP to project hosts
  lineinfile:
    dest: "{{ANSIBLE_HOMEPATH}}hosts"
    regexp: "{{ item.private_ip }}"
    insertafter: "\\[{{outer_item.SECTION}}\\]"
    line: "{{ item.private_ip }}"
  with_items: "{{ ec2.tagged_instances }}"
